### ISSUE TITLE
I am getting these errors when running gradle build 

### ISSUE THREAD

**Issue by rsn93323** [avik-das/build-your-own-raytracer-java#1]
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\image\Image.java:22: error: cannot find symbol
                        color.getR(),
                             ^
  symbol:   method getR()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\image\Image.java:23: error: cannot find symbol
                        color.getG(),
                             ^
  symbol:   method getG()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\image\Image.java:24: error: cannot find symbol
                        color.getB()
                             ^
  symbol:   method getB()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\image\ReadableImage.java:20: error: constructor ReadableImage in class ReadableImage cannot be applied to given types;
        return new ReadableImage(image);
               ^
  required: no arguments
  found: BufferedImage
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\image\ReadableImage.java:37: error: constructor ImageColor in class ImageColor cannot be applied to given types;
        return new ImageColor(r, g, b);
               ^
  required: no arguments
  found: int,int,int
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:19: error: constructor Vector3 in class Vector3 cannot be applied to given types;
            new Vector3(0, 0, 2),
            ^
  required: no arguments
  found: int,int,int
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:21: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                    new Vector3(-1.92f,  1.08f, -0.5f),
                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:22: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                    new Vector3( 1.92f,  1.08f, -0.5f),
                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:23: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                    new Vector3(-1.92f, -1.08f, -0.5f),
                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:24: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                    new Vector3( 1.92f, -1.08f, -0.5f)
                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:26: error: constructor Color in class Color cannot be applied to given types;
            new Color(0.5f, 0.5f, 0.5f),
            ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:41: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(0, 0, -1.2f),
                            ^
  required: no arguments
  found: int,int,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:44: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.2f, 0.1f, 0.1f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:45: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.4f, 0.1f, 0.1f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:46: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.7f, 0.7f, 0.7f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:47: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.9f, 0.5f, 0.5f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:53: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(-1, 0, -0.8f),
                            ^
  required: no arguments
  found: int,int,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:56: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.1f, 0.2f, 0.1f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:57: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.5f, 0.9f, 0.5f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:58: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.7f, 0.7f, 0.7f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:59: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.3f, 0.5f, 0.2f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:65: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(1, 0f, -0.8f),
                            ^
  required: no arguments
  found: int,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:68: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.1f, 0.1f, 0.2f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:69: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.5f, 0.5f, 0.9f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:70: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.7f, 0.7f, 0.7f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:71: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.2f, 0.3f, 0.5f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:77: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(0, 0.7f, -0.8f),
                            ^
  required: no arguments
  found: int,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:80: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.1f, 0.1f, 0.2f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:81: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.9f, 0.5f, 0.5f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:82: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.7f, 0.7f, 0.7f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:83: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.5f, 0.2f, 0.3f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:89: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(0, -0.7f, -0.8f),
                            ^
  required: no arguments
  found: int,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:92: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.1f, 0.1f, 0.2f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:93: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.9f, 0.5f, 0.9f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:94: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.7f, 0.7f, 0.7f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:95: error: constructor Color in class Color cannot be applied to given types;
                                    new Color(0.5f, 0.2f, 0.5f),
                                    ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:29: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(-5, 1, 0.5f),
                            ^
  required: no arguments
  found: int,int,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:30: error: constructor Color in class Color cannot be applied to given types;
                            new Color(0.8f, 0.8f, 0.8f),
                            ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:31: error: constructor Color in class Color cannot be applied to given types;
                            new Color(0.8f, 0.8f, 0.8f)
                            ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:34: error: constructor Vector3 in class Vector3 cannot be applied to given types;
                            new Vector3(5, -1, 0.5f),
                            ^
  required: no arguments
  found: int,int,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:35: error: constructor Color in class Color cannot be applied to given types;
                            new Color(0.7f, 0.7f, 0.7f),
                            ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:36: error: constructor Color in class Color cannot be applied to given types;
                            new Color(0.8f, 0.8f, 0.8f)
                            ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:114: error: constructor RayTracer in class RayTracer cannot be applied to given types;
                new com.avikdas.raytracer.tracer.RayTracer(SCENE, W, H);
                ^
  required: no arguments
  found: Scene,int,int
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:129: error: cannot find symbol
                (int) (color.getR() * ImageColor.MAX),
                            ^
  symbol:   method getR()
  location: variable color of type Color
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:130: error: cannot find symbol
                (int) (color.getG() * ImageColor.MAX),
                            ^
  symbol:   method getG()
  location: variable color of type Color
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:131: error: cannot find symbol
                (int) (color.getB() * ImageColor.MAX)
                            ^
  symbol:   method getB()
  location: variable color of type Color
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\RayTracer.java:128: error: constructor ImageColor in class ImageColor cannot be applied to given types;
        return new ImageColor(
               ^
  required: no arguments
  found: int,int,int
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Texture.java:17: error: constructor Texture in class Texture cannot be applied to given types;
        return new Texture(ReadableImage.fromResource(resource));
               ^
  required: no arguments
  found: ReadableImage
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Texture.java:27: error: cannot find symbol
                (float) color.getR() / ImageColor.MAX,
                             ^
  symbol:   method getR()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Texture.java:28: error: cannot find symbol
                (float) color.getG() / ImageColor.MAX,
                             ^
  symbol:   method getG()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Texture.java:29: error: cannot find symbol
                (float) color.getB() / ImageColor.MAX
                             ^
  symbol:   method getB()
  location: variable color of type ImageColor
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Texture.java:26: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:8: error: constructor Color in class Color cannot be applied to given types;
    public static final Color BLACK = new Color(0, 0, 0);
                                      ^
  required: no arguments
  found: int,int,int
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:15: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:23: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:31: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:39: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Color.java:47: error: constructor Color in class Color cannot be applied to given types;
        return new Color(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Vector3.java:12: error: constructor Vector3 in class Vector3 cannot be applied to given types;
        return new Vector3(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Vector3.java:20: error: constructor Vector3 in class Vector3 cannot be applied to given types;
        return new Vector3(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Vector3.java:28: error: constructor Vector3 in class Vector3 cannot be applied to given types;
        return new Vector3(
               ^
  required: no arguments
  found: float,float,float
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Material.java:19: error: cannot find symbol
        float x = normal.getX();
                        ^
  symbol:   method getX()
  location: variable normal of type Vector3
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Material.java:20: error: cannot find symbol
        float y = normal.getY();
                        ^
  symbol:   method getY()
  location: variable normal of type Vector3
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Material.java:21: error: cannot find symbol
        float z = normal.getZ();
                        ^
  symbol:   method getZ()
  location: variable normal of type Vector3
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Sphere.java:9: error: Sphere is not abstract and does not override abstract method getMaterial() in SceneObject
public class Sphere implements SceneObject {
       ^
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Sphere.java:16: error: cannot find symbol
        Vector3 cPrime = ray.getOrigin().minus(center);
                            ^
  symbol:   method getOrigin()
  location: variable ray of type Ray
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Sphere.java:17: error: cannot find symbol
        float a = ray.getDirection().dot(ray.getDirection());
                     ^
  symbol:   method getDirection()
  location: variable ray of type Ray
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Sphere.java:17: error: cannot find symbol
        float a = ray.getDirection().dot(ray.getDirection());
                                            ^
  symbol:   method getDirection()
  location: variable ray of type Ray
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\scene\Sphere.java:18: error: cannot find symbol
        float b = 2 * cPrime.dot(ray.getDirection());
                                    ^
  symbol:   method getDirection()
  location: variable ray of type Ray
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:44: error: cannot find symbol
                scene.getImagePlane().getTopLeft(),
                     ^
  symbol:   method getImagePlane()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:45: error: cannot find symbol
                scene.getImagePlane().getTopRight(),
                     ^
  symbol:   method getImagePlane()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:50: error: cannot find symbol
                scene.getImagePlane().getBottomLeft(),
                     ^
  symbol:   method getImagePlane()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:51: error: cannot find symbol
                scene.getImagePlane().getBottomRight(),
                     ^
  symbol:   method getImagePlane()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:58: error: cannot find symbol
                point.minus(scene.getCamera())
                                 ^
  symbol:   method getCamera()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:66: error: cannot find symbol
                .getObjects()
                ^
  symbol:   method getObjects()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:80: error: cannot find symbol
                    Vector3 view = ray.getDirection().inverted().normalized();
                                      ^
  symbol:   method getDirection()
  location: variable ray of type Ray
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:98: error: constructor Ray in class Ray cannot be applied to given types;
                                new Ray(point, reflection)
                                ^
  required: no arguments
  found: Vector3,Vector3
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:125: error: cannot find symbol
                .getLights()
                ^
  symbol:   method getLights()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:144: error: cannot find symbol
                                    r.dot(view), material.getAlpha()));
                                                         ^
  symbol:   method getAlpha()
  location: variable material of type Material
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:142: error: cannot find symbol
                            .times(material.getKSpecular())
                                           ^
  symbol:   method getKSpecular()
  location: variable material of type Material
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:151: error: cannot find symbol
                .getKAmbient()
                ^
  symbol:   method getKAmbient()
  location: variable material of type Material
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:152: error: cannot find symbol
                .times(scene.getAmbientLight());
                            ^
  symbol:   method getAmbientLight()
  location: variable scene of type Scene
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:162: error: cannot find symbol
        Vector3 direction = light.getPosition().minus(point);
                                 ^
  symbol:   method getPosition()
  location: variable light of type Light
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:163: error: constructor Ray in class Ray cannot be applied to given types;
        Ray shadowRay = new Ray(point, direction);
                        ^
  required: no arguments
  found: Vector3,Vector3
  reason: actual and formal argument lists differ in length
C:\Users\Rupert\build-your-own-raytracer-java\src\main\java\com\avikdas\raytracer\tracer\RayTracer.java:166: error: cannot find symbol
                .getObjects()
                ^
  symbol:   method getObjects()
  location: variable scene of type Scene
85 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by rsn93323** [comment]
java version:

java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)


------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          12.0.2 (Oracle Corporation 12.0.2+10)
OS:           Windows 10 10.0 amd64

**Comment by avik-das** [comment]
@rsn93323 Thanks for reporting! I tracked this down to how I was configuring [Lombok](https://projectlombok.org/), which is how I generate the getters, setters, constructors, etc. I've fixed the issue.

Because I need the build to work for all the historical commits I have, I had to rewrite the commit history. You'll have to re-clone the repository. Please let me know if it doesn't work. Thanks!

**Comment by rsn93323** [comment]
BUILD SUCCESSFUL in 18s
7 actionable tasks: 7 executed

That fixed it! Thank you. I was not expecting such a quick response. Good stuff.
