### ISSUE TITLE
Java build failure

### ISSUE THREAD

**Issue by ofluffydev** [avik-das/build-your-own-raytracer-java#2]
The project is unusable and gradle build fails no matter what. I will attempt to fix it and submit a pull request but until then please fix your gradle files.

**Comment by avik-das** [comment]
@ofluffydev: I didn't have time to get to this earlier, but I upgraded the lombok gradle plugin. The build should work now.

If you still run into issues, feel free to re-open, but please make sure to provide any logging output. Right now, the build works on my machine, so without any logging output, I won't be able to debug. Thanks!
